### ISSUE TITLE
Notification to alert DB connection is back up should not be logged at error level

### ISSUE THREAD

**Issue by squ1d123** [ebean-orm/ebean-datasource#55]
Is there a reason that `Log.error("RESOLVED FATAL: DataSourcePool [" + name + "] is back up!");` is logged at `ERROR` level?

This seems strange as this is a notification that the connection to the datasouce is back up.

This leads to misleading understanding of the system.

Typically something logged at `ERROR` means something has gone wrong.

Reference [notifyUp](https://github.com/ebean-orm/ebean-datasource/blob/master/ebean-datasource/src/main/java/io/ebean/datasource/pool/ConnectionPool.java#L346)

**Comment by rbygrave** [comment]
The reasons this is logged at ERROR level is because:

1. We want to see the message and there is a chance that we would not see the message at WARNING level.  That is, the message is so important that we absolutely want people to see it.  (An important "Anti-ERROR" message, the same importance as the original ERROR message it relates to)

2. In this sort of situation we are often looking at logs and filtering them on ERROR level (only looking at error level messages).  In that case it is beneficial for the "Anti-Error" "RESOLVED FATAL" message to also show up in that same search. In the search for errors we see when the datasource was considered down and when it came back up / resolved - we don't need a more sophisticated log search to determine that.


> something logged at ERROR means something has gone wrong.

Yes typically. In this case its more that the message is so important we want it to be seen/visible at the same level as the original FATAL DataSourcePool down message.


Is there something specific in terms of tooling / alerting that is impacted by this being logged at ERROR?

**Comment by rbygrave** [comment]
I will close this @squ1d123 - you can reopen if needed.

**Comment by rob-bygrave** [comment]
Well you know what ... I think you were right all along, and I've gone and changed my mind on this so yeah dropping it to INFO level. Gee, it only took me ... looks like around 4 years. FWIW: This question / issue was somewhere in the back of my brain. I had a chat to someone recently about a DEV environment that is shutdown ever night to save costs etc and I guess that somehow linked back to this question. 

https://github.com/ebean-orm/ebean-datasource/pull/151
